-- MySQL Script generated by MySQL Workbench
-- Wed Feb 11 22:13:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pazienti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pazienti` (
  `idtable1` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `data_di_nascita` DATE NOT NULL,
  `luogo_di_nascita` VARCHAR(60) NOT NULL,
  `indirizzo_di_residenza` VARCHAR(60) NOT NULL,
  `cap` VARCHAR(10) NOT NULL,
  `cellulare` VARCHAR(20) NOT NULL,
  `codice_fiscale` VARCHAR(16) NOT NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`idtable1`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `codice_fiscale_UNIQUE` (`codice_fiscale` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dottore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dottore` (
  `iddottore` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cognome` VARCHAR(45) NOT NULL,
  `cellulare` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `partita_iva` VARCHAR(45) NULL,
  `pazienti_idtable1` INT NOT NULL,
  PRIMARY KEY (`iddottore`),
  INDEX `fk_dottore_pazienti_idx` (`pazienti_idtable1` ASC) ,
  CONSTRAINT `fk_dottore_pazienti`
    FOREIGN KEY (`pazienti_idtable1`)
    REFERENCES `mydb`.`pazienti` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
